site_name: CSS-Watchdog
theme:
  name: 'material'
  logo: 'images/wd.svg'
repo_name: 'loukas-kotas/css-watchdog-docs'
repo_url: 'https://github.com/loukas-kotas/css-watchdog-docs'
nav:
  - Library: lib.md
  - API: api.md  
  - CLI: cli.md
extra_css:
  - css/style.css